services:
  postgres:
    image: postgres:14
    container_name: retail_analytics_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retail_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/database/init-scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - retail_analytics_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retail_user -d retail_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:5
    container_name: retail_analytics_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: retail_user
      MONGO_INITDB_ROOT_PASSWORD: retail_password
      MONGO_INITDB_DATABASE: retail_analytics
    volumes:
      - mongodb_data:/data/db
      - ./config/database/init-scripts/mongodb:/docker-entrypoint-initdb.d
    networks:
      - retail_analytics_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/retail_analytics --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: retail_analytics_redis
    command: redis-server --requirepass retail_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - retail_analytics_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "retail_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: retail_analytics_adminer
    ports:
      - "8080:8080"
    networks:
      - retail_analytics_network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  mongo-express:
    image: mongo-express
    container_name: retail_analytics_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: retail_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: retail_password
      ME_CONFIG_MONGODB_URL: mongodb://retail_user:retail_password@mongodb:27017/
    networks:
      - retail_analytics_network
    depends_on:
      - mongodb

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  retail_analytics_network:
    driver: bridge